export const products = [
  {
    id: 0,
    name: "Iphone 11",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "iphone",
    price: 2999.99,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/26/2652093/Smartfon-APPLE-iPhone-11--Black-Front-Tyl.jpg",
    // image: "./images/iphone-11.jpg",
    sale: true,
    saleAmount: 200,
    amount: 1,
  },
  {
    id: 1,
    name: "Iphone 13",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "iphone",
    price: 5200.99,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/32/3225338/APPLE_iPhone_13__front_czerwony.jpg",
    saleAmount: 0,
    amount: 1,
  },
  {
    id: 2,
    name: "Iphone 12",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "iphone",
    price: 4444.44,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/29/2958646/Smartfon-APPLE-iPhone-12-5G-Purpurowy-01.jpg",
    sale: true,
    saleAmount: 451,
    amount: 1,
  },
  {
    id: 3,
    name: "huawei p50 pro",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "huawei",
    price: 1330,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/34/3436768/Smartfon-HUAWEI-P50-Pro-8-256GB-Czarny-front-i-tyl.jpg",
    saleAmount: 0,
    amount: 1,
  },
  {
    id: 4,
    name: "huawei y70",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "huawei",
    price: 899,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/38/3866670/Smartfon-Huawei-Nova-Y70-Niebieski-Front-Plecki.jpg",
    saleAmount: 0,
    amount: 1,
  },
  {
    id: 5,
    name: "Nokia g21",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "nokia",
    price: 950,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/36/3662252/Smartfon-NOKIA-G21-4-64GB-Niebieski-front-tyl.jpg",
    sale: true,
    saleAmount: 250,
    amount: 1,
  },
  {
    id: 6,
    name: "Nokia 230",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "nokia",
    price: 690,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/30/3064132/Smartfon-NOKIA-X10-6-64GB-6-67-5G-Zielony-front-tyl.jpg",
    saleAmount: 0,
    amount: 1,
  },
  {
    id: 7,
    name: "Samsung a53",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "samsung",
    price: 1440,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/36/3615683/Smartfon-SAMSUNG-Galaxy-A53-5G-6-128GB-Bialy-SM-A536-front-tyl.jpg",
    saleAmount: 0,
    amount: 1,
  },
  {
    id: 8,
    name: "Samsung s20",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "samsung",
    price: 2620.2,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/25/2501370/Smartfon-SAMSUNG-Galaxy-S20-FE-5G-SM-G781-Niebieski-tyl-front.jpg",
    sale: true,
    saleAmount: 300,
    amount: 1,
  },
  {
    id: 9,
    name: "Samsung s22",
    description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
    category: "samsung",
    price: 3399.99,
    image:
      "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/35/3508342/Smartfon-SAMSUNG-Galaxy-S22-Czarny-1.jpg",
    saleAmount: 0,
    amount: 1,
  },
];
